config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :events do
    member do
      post :publish
      post :unpublish
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord  
  belongs_to :user

  validates :name, :description, :address, :duration, presence: true
  validates :price, presence: :true, if: :paid? 

  enum status: [:unpublished, :published]
  enum costing: [:free, :paid]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_event, only: %i[ show edit update destroy publish unpublish ]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit;end

  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def publish
    if @event.published!
      flash[:success] = 'Event Published'
    else
      flash[:error] = 'Event could not be Published'
    end

    redirect_to @event
  end

  def unpublish
    if @event.unpublished!
      flash[:success] = 'Event Unpublished'
    else
      flash[:error] = 'Event could not be Unpublished'
    end

    redirect_to @event
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :user_id, :description, :status, :costing, :price, :duration, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = Event.published.ransack(params[:q])
    @published_events = @q.result
    @pagy, @events = pagy(@published_events.order(created_at: :desc))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
<div class="container mx-auto flex justify-center">
  <div class="text-indigo-400 w-5/12">

    <%= form_with(model: event, local: true) do |form| %>
      <% if event.errors.any? %>
        <div id="error_explanations" class="bg-red-200 text-red-700 px-4 py-2 my-3">
          <h2 class="text-2xl"><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="fields">
        <%= form.label :name %>
        <%= form.text_field :name, class: "px-4 py-2 my-2 w-full rounded-lg border text-gray-700" %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description, class: "px-4 py-2 my-2 w-full rounded-lg border text-gray-700" %>
      </div>


      <div class="field">
        <%= form.label :costing %>
        <%= form.select(:costing, Event.costings.keys.map {|cost| [cost.titleize,cost]}, {},class: "px-4 py-2 my-2 w-full rounded-lg border text-gray-700") %>
      </div>

      <div class="field">
        <%= form.label :price %>
        <%= form.text_field :price, placeholder: "leave empty for free events", class: "px-4 py-2 my-2 w-full rounded-lg border text-gray-700" %>
      </div>

      <div class="field">
        <%= form.label :duration, 'Duration in hours'%>
        <%= form.number_field :duration, class: "px-4 py-2 my-2 w-full rounded-lg border text-gray-700" %>
      </div>

      <div class="field">
        <%= form.label :address %>
        <%= form.text_area :address, class: "px-4 py-2 my-2 w-full rounded-lg border text-gray-700" %>
      </div>

      <div class="actions">
        <%= form.submit 'Submit' , class: "px-4 py-2 my-2 text-white bg-indigo-500 rounded-lg w-full" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="container mx-auto">

<h1 class="text-indigo-400 text-3xl text-center my-2">Events</h1>
<div class="text-indigo-100 mb-3 flex justify-end">
  <%= link_to 'New Event', new_event_path, class: 'justify-end bg-indigo-500 rounded-full px-4 py-2' %>
</div>

<table class="w-full shadow-lg layout-auto">
  <thead>
    <tr>
      <th class="px-4 py-3">Name</th>
      <th class="px-4 py-3">Description</th>
      <th class="px-4 py-3">Status</th>
      <th class="px-4 py-3">Costing</th>
      <th class="px-4 py-3">Price</th>
      <th class="px-4 py-3">Duration</th>
      <th class="px-4 py-3">Address</th>
      <th colspan="3" class="px-4 py-3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr class="w-full font-light text-gray-700 bg-gray-100 whitespace-no-wrap border border-b-0">
        <td class="px-4 py-4"><%= event.name %></td>
        <td class="px-4 py-4"><%= truncate(event.description, length: 50) %></td>
        <td class="px-4 py-4"><%= event.status %></td>
        <td class="px-4 py-4">
          <span class="#{ event.costing.free? ? bg-green-100 : bg-green-400 } px-4 py-2 rounded-full">
          <%= event.costing %>
          </span>
        </td>
        <td class="px-4 py-4"><%= event.price %></td>
        <td class="px-4 py-4"><%= "#{event.duration} hrs" %></td>
        <td class="px-4 py-4"><%= truncate(event.address, length: 25) %></td>
        <td class="px-4 py-4"><%= link_to 'Show', event %></td>
        <td class="px-4 py-4"><%= link_to 'Edit', edit_event_path(event) %></td>
        <td class="px-4 py-4"><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

app/views/events/new.html.erb
<h1 class="text-indigo-500 text-center text-4xl my-3">New Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<div class="container mx-auto flex justify-center">
  <div class="w-6/12 px-4 py-2">
    <p id="notice"><%= notice %></p>
<div class="flex justify-between">
<h1 class="text-center text-indigo-300 text-3xl"> <%= @event.name %></h1>
  <div class="flex ">
    <h1 class="text-center text-gray-500 mb-4 text-2xl"> <%= "#{@event.duration}hrs" %></h1>

    <% if user_signed_in? and current_user == @event.user %>
      <% unless @event.published? %>
        <%= link_to "Publish", publish_event_path(@event), method: :post, class: "text-sm ml-3 px-6 py-2 bg-green-300 rounded-lg text-white" %>
      <% else %>
        <%= link_to "Unpublish" ,  unpublish_event_path(@event), method: :post, class: "text-xs ml-3 px-6 py-2 bg-indigo-500 rounded-lg text-white" %>
      <% end %>
    <% end %>

  </div>
</div>



<div class="my-3 justify-between flex">

  <span class="<%= @event.free? ? 'bg-yellow-200' : 'bg-green-300' %> px-4 py-2 rounded-lg">
    <%= @event.costing %>
  </span>

  <% if @event.paid? %>
    <p>
      <strong>Price:</strong>
      <span class="px-4 py-2 bg-green-100 rounded-lg"> 
        <%= @event.price %>
      </span>
  </p>
  <%end%>

  <p>
    <strong>Status:</strong>
    <%= @event.status %>
  </p>
</div>


<p class="w-full text-gray-700">
  <%= @event.description %>
</p>

<p>
  <strong>Address:</strong>
  <span class="text-2xl text-gray-600">
    <%= @event.address %>
  </span>
</p>
  </div>

</div>

app/views/home/index.html.erb
<div class="container mx-auto  w-full">
  <div class="">
    <h1 class="text-indigo-500 text-2xl mt-3"> Events</h1>
      <div class="flex flex-wrap justify-center"> 
        <% @events.each do |event| %>
            <div class="bg-indigo-400 rounded-lg p-5 text-white max-w-xs my-4 mx-2 w-6/12">
              <h1 class="text-3xl text-center font-black-500"> <%= event.name %> </h1>
              <p class="mt-4 font-tight text-center mb-4">
                <%= truncate(event.description, length: 50) %>
              </p>
              <%= button_to 'View', event_path(event), method: :get, class:"rounded-lg bg-indigo-600 px-4 py-2 text-white hover:bg-indigo-700 px-4 py-2 w-full" %>
            </div>
        <%end %>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/nav' %>
    <% flash.each do |name, msg| %>
      <div class="<%= name ==  'alert' ? 'bg-yellow-200' : 'bg-green-300' %>  flex justify-between items-center relative text-gray-600 py-3 px-3 mt-4 ">
        <span>
          <%= msg %>
        </span>
      </div>      
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="flex items-center justify-between flex-wrap bg-indigo-400 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <span class="font-semibold text-xl tracking-tight">Tickets!</span>
  </div>
  <div class="block md:hidden">
    <button @click="show=!show" class="flex items-center px-3 py-2 border rounded text-gray-100 border-gray-200 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" ><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div  class="w-full block flex-grow md:flex md:justify-end md:w-auto text-white">
    <div>
      <%= link_to 'Home', root_path, class: "block md:inline-block text-sm px-4 py-2 leading-none rounded text-white border-white hover:border-transparent  hover:bg-indigo-600 mt-4 md:mt-0" %>
      <% unless user_signed_in? %>
        <%= link_to 'Log in', new_user_session_path, class: "block md:inline-block text-sm px-4 py-2 leading-none rounded text-white border-white hover:border-transparent hover:bg-indigo-600 mt-4 md:mt-0" %>
        <%= link_to 'Sign up', new_user_registration_path, class: "block md:inline-block text-sm px-4 py-2 leading-none rounded text-white border-white hover:border-transparent hover:bg-indigo-600 mt-4 md:mt-0" %>

      <% else %>
          <%= link_to 'Create Event', new_event_path, class: "block md:inline-block text-sm px-4 py-2 leading-none rounded text-white border-white hover:border-transparent hover:bg-indigo-600 mt-4 md:mt-0" %>
          <%= link_to 'My Events', events_path, class: "block md:inline-block text-sm px-4 py-2 leading-none rounded text-white border-white hover:border-transparent hover:bg-indigo-600 mt-4 md:mt-0" %>

        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "block md:inline-block text-sm px-4 py-2 leading-none rounded text-white border-white hover:border-transparent hover:bg-indigo-600 mt-4 md:mt-0" %>
      <% end %>  
    </div>
  </div>
</nav>